import React, { useEffect, useState } from 'react'
import { motion } from 'framer-motion'
import toast from 'react-hot-toast'
import { fetchReportSummary, fetchPopularBooks } from '../../services/reportService'
import { fetchBooks } from '../../services/bookService'
import { fetchMembers } from '../../services/memberService'
import { fetchLoans } from '../../services/loanService'
import Modal from '../../components/Modal'

function formatDateShort(date) {
  if (!date) return '—'
  return new Date(date).toLocaleString()
}

function formatDateCompact(date) {
  if (!date) return '—'
  return new Date(date).toISOString().slice(0, 10)
}

function safeCsv(value) {
  if (value == null) return ''
  const str = String(value).replace(/"/g, '""')
  return `"${str.replace(/\n/g, ' ')}"`
}

function downloadFile(filename, content, type) {
  const blob = new Blob([content], { type })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

export default function Reports() {
  const [summary, setSummary] = useState(null)
  const [popular, setPopular] = useState([])
  const [books, setBooks] = useState([])
  const [members, setMembers] = useState([])
  const [loading, setLoading] = useState(false)
  const [viewMember, setViewMember] = useState(null)

  const loadAll = async () => {
    setLoading(true)
    try {
      const [s, p, b] = await Promise.all([
        fetchReportSummary(),
        fetchPopularBooks(),
        fetchBooks({ page: 1, limit: 1000 }),
      ])
      setSummary(s)
      setPopular(Array.isArray(p) ? p.slice(0, 5) : [])
      setBooks(Array.isArray(b?.data) ? b.data : [])

      // load members for table (first 100)
      const membersRes = await fetchMembers({ page: 1, limit: 100 })
      setMembers(membersRes?.data || [])
    } catch (err) {
      console.error(err)
      toast.error('Failed loading reports')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    loadAll()
    const id = setInterval(loadAll, 5000)
    return () => clearInterval(id)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])


  const generateMemberPDF = async (member) => {
    try {
      const res = await fetchLoans({ member: member._id, page: 1, limit: 1000 })
      const loans = res?.data || []
      const date = new Date()
      const filename = `${member.fullName.replace(/\s+/g,'_')}_Report.pdf`
      const rows = loans.map((l) => `
          <tr>
            <td>${l.book?.title || '—'}</td>
            <td>${l.borrowedAt ? new Date(l.borrowedAt).toLocaleString() : '—'}</td>
            <td>${l.dueAt ? new Date(l.dueAt).toLocaleString() : '—'}</td>
            <td>${l.returnedAt ? new Date(l.returnedAt).toLocaleString() : '—'}</td>
            <td>${l.status || '—'}</td>
          </tr>
        `).join('')
      const html = `<!doctype html><html><head><meta charset="utf-8"><title>${filename}</title><style>body{font-family:Inter,system-ui,Arial;padding:24px;color:#111827;} h1{margin:0 0 12px;} h2{margin:14px 0 8px;} table{width:100%;border-collapse:collapse;margin-top:12px;} th,td{border:1px solid #e5e7eb;padding:10px;text-align:left;} .header-card{border:1px solid #e5e7eb;padding:16px;border-radius:14px;margin-bottom:14px;} .stats-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-bottom:14px;} .stat-cell{border:1px solid #e5e7eb;padding:12px;border-radius:12px;} .footer{margin-top:24px;font-size:12px;color:#6b7280;}</style></head><body>`
        + `<h1>LibroSphere Member Report</h1><div class="header-card"><h2>Member Details</h2><div><strong>Name:</strong> ${member.fullName}</div><div><strong>Membership ID:</strong> ${member.membershipId}</div><div><strong>Email:</strong> ${member.email || '—'}</div><div><strong>Phone:</strong> ${member.phone || '—'}</div><div><strong>Address:</strong> ${member.address || '—'}</div><div><strong>Member Since:</strong> ${member.joinedAt || member.createdAt || '—'}</div></div>`
        + `<div class="stats-grid"><div class="stat-cell"><strong>Books Borrowed</strong><div>${member.totalBorrowedCount ?? 0}</div></div><div class="stat-cell"><strong>Books Returned</strong><div>${(member.totalBorrowedCount ?? 0) - (member.currentBorrowedCount ?? 0)}</div></div><div class="stat-cell"><strong>Currently Borrowed</strong><div>${member.currentBorrowedCount ?? 0}</div></div><div class="stat-cell"><strong>Overdue Books</strong><div>${member.overdueCount ?? 0}</div></div></div>`
        + `<h2>Complete Borrow History</h2><table><thead><tr><th>Book</th><th>Borrow Date</th><th>Due Date</th><th>Return Date</th><th>Status</th></tr></thead><tbody>${rows}</tbody></table>`
        + `<div class="footer">Generated by LibroSphere Library Management System<br/>Generated On: ${date.toLocaleString()}</div>`
        + `</body></html>`

      const win = window.open('', '_blank')
      if (!win) return toast.error('Unable to open print window')
      win.document.open()
      win.document.write(html)
      win.document.close()
      win.focus()
      setTimeout(()=>{ win.print(); }, 600)
    } catch (err) {
      console.error(err)
      toast.error('Failed to generate member PDF')
    }
  }

  const generateLibraryPDF = async () => {
    try {
      const [summaryData, popularBooks, allLoans] = await Promise.all([
        fetchReportSummary(),
        fetchPopularBooks(),
        fetchLoans({ page: 1, limit: 1000 }),
      ])
      const date = new Date()
      const filename = `LibroSphere_Report_${formatDateCompact(date)}.pdf`
      const borrowRecords = allLoans?.data || []
      const returnRecords = borrowRecords.filter((loan) => loan.returnedAt)
      const memberStats = members.map((m) => ({
        fullName: m.fullName,
        membershipId: m.membershipId,
        borrowed: m.totalBorrowedCount ?? 0,
        returned: m.totalBorrowedCount != null && m.currentBorrowedCount != null ? (m.totalBorrowedCount - m.currentBorrowedCount) : 0,
        currentlyBorrowed: m.currentBorrowedCount ?? 0,
        overdue: m.overdueCount ?? 0,
      }))

      const popularRows = popularBooks.slice(0, 5).map((book, i) => `
          <tr>
            <td>${i + 1}</td>
            <td>${book.title || '—'}</td>
            <td>${book.author || '—'}</td>
            <td>${book.count ?? 0}</td>
          </tr>
        `).join('')
      const activityRows = memberStats.map((stat) => `
          <tr>
            <td>${stat.fullName}</td>
            <td>${stat.membershipId}</td>
            <td>${stat.borrowed}</td>
            <td>${stat.returned}</td>
            <td>${stat.currentlyBorrowed}</td>
            <td>${stat.overdue}</td>
          </tr>
        `).join('')
      const borrowRows = borrowRecords.map((loan) => `
          <tr>
            <td>${loan.book?.title || '—'}</td>
            <td>${loan.member?.fullName || '—'}</td>
            <td>${loan.member?.membershipId || '—'}</td>
            <td>${loan.borrowedAt ? new Date(loan.borrowedAt).toLocaleString() : '—'}</td>
            <td>${loan.dueAt ? new Date(loan.dueAt).toLocaleString() : '—'}</td>
            <td>${loan.status || '—'}</td>
          </tr>
        `).join('')
      const returnedRows = returnRecords.map((loan) => `
          <tr>
            <td>${loan.book?.title || '—'}</td>
            <td>${loan.member?.fullName || '—'}</td>
            <td>${loan.member?.membershipId || '—'}</td>
            <td>${loan.borrowedAt ? new Date(loan.borrowedAt).toLocaleString() : '—'}</td>
            <td>${loan.dueAt ? new Date(loan.dueAt).toLocaleString() : '—'}</td>
            <td>${loan.returnedAt ? new Date(loan.returnedAt).toLocaleString() : '—'}</td>
            <td>${loan.status || '—'}</td>
          </tr>
        `).join('')

      const html = `<!doctype html><html><head><meta charset="utf-8"><title>${filename}</title><style>body{font-family:Inter,system-ui,Arial;padding:24px;color:#111827;} h1{margin:0 0 12px;} h2{margin:14px 0 8px;} table{width:100%;border-collapse:collapse;margin-top:12px;} th,td{border:1px solid #e5e7eb;padding:10px;text-align:left;} .header-row{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px;} .section{margin-bottom:24px;} .footer{margin-top:24px;font-size:12px;color:#6b7280;}</style></head><body>`
        + `<div class="header-row"><div><h1>LibroSphere Report</h1><div>${date.toLocaleString()}</div></div><div>Generated by LibroSphere Library Management System</div></div>`
        + `<div class="section"><h2>Library Summary</h2><table><tbody>`
        + `<tr><th>Total Books</th><td>${summaryData.totalBooks ?? 0}</td></tr>`
        + `<tr><th>Registered Members</th><td>${summaryData.totalMembers ?? 0}</td></tr>`
        + `<tr><th>Total Borrows</th><td>${summaryData.totalBorrows ?? 0}</td></tr>`
        + `<tr><th>Total Returns</th><td>${summaryData.totalReturns ?? 0}</td></tr>`
        + `<tr><th>Available Books</th><td>${summaryData.availableBooks ?? 0}</td></tr>`
        + `<tr><th>Overdue Books</th><td>${summaryData.overdueLoans ?? 0}</td></tr>`
        + `<tr><th>Return Rate</th><td>${summaryData.returnRate ?? 0}%</td></tr>`
        + `</tbody></table></div>`
        + `<div class="section"><h2>Most Borrowed Books</h2><table><thead><tr><th>#</th><th>Title</th><th>Author</th><th>Borrows</th></tr></thead><tbody>${popularRows}</tbody></table></div>`
        + `<div class="section"><h2>Member Activity Summary</h2><table><thead><tr><th>Member</th><th>Membership ID</th><th>Borrowed</th><th>Returned</th><th>Currently Borrowed</th><th>Overdue</th></tr></thead><tbody>${activityRows}</tbody></table></div>`
        + `<div class="section"><h2>Borrow Records</h2><table><thead><tr><th>Book</th><th>Member</th><th>Membership ID</th><th>Borrow Date</th><th>Due Date</th><th>Status</th></tr></thead><tbody>${borrowRows}</tbody></table></div>`
        + `<div class="section"><h2>Return History</h2><table><thead><tr><th>Book</th><th>Member</th><th>Membership ID</th><th>Borrow Date</th><th>Due Date</th><th>Return Date</th><th>Status</th></tr></thead><tbody>${returnedRows}</tbody></table></div>`
        + `<div class="footer">Generated by LibroSphere Library Management System</div>`
        + `</body></html>`

      const win = window.open('', '_blank')
      if (!win) return toast.error('Unable to open print window')
      win.document.open()
      win.document.write(html)
      win.document.close()
      win.focus()
      setTimeout(()=>{ win.print(); }, 600)
    } catch (err) {
      console.error(err)
      toast.error('Failed to generate library PDF')
    }
  }

  const exportLibraryCSV = async () => {
    try {
      const loansRes = await fetchLoans({ page: 1, limit: 1000 })
      const loanData = loansRes?.data || []
      const headers = ['Books', '', '', '']
      const bookLines = ['Title,Author,ISBN,Category,Copies']
      bookLines.push(...books.map((book) => [
        safeCsv(book.title),
        safeCsv(book.author),
        safeCsv(book.isbn || ''),
        safeCsv(book.category || ''),
        safeCsv(book.copies ?? 0),
      ].join(',')))

      const memberLines = ['\nMembers', '', '', '', '']
      memberLines.push('Full Name,Membership ID,Email,Phone,Address,Joined At,Books Borrowed,Currently Borrowed,Overdue')
      memberLines.push(...members.map((member) => [
        safeCsv(member.fullName),
        safeCsv(member.membershipId),
        safeCsv(member.email || ''),
        safeCsv(member.phone || ''),
        safeCsv(member.address || ''),
        safeCsv(formatDateCompact(member.joinedAt || member.createdAt)),
        safeCsv(member.totalBorrowedCount ?? 0),
        safeCsv(member.currentBorrowedCount ?? 0),
        safeCsv(member.overdueCount ?? 0),
      ].join(',')))

      const borrowLines = ['\nBorrow Records', '', '', '', '', '', '']
      borrowLines.push('Book,Member,Membership ID,Borrowed At,Due At,Status')
      borrowLines.push(...loanData.map((loan) => [
        safeCsv(loan.book?.title || ''),
        safeCsv(loan.member?.fullName || ''),
        safeCsv(loan.member?.membershipId || ''),
        safeCsv(loan.borrowedAt ? new Date(loan.borrowedAt).toLocaleString() : ''),
        safeCsv(loan.dueAt ? new Date(loan.dueAt).toLocaleString() : ''),
        safeCsv(loan.status || ''),
      ].join(',')))

      const returnLines = ['\nReturn Records', '', '', '', '', '', '', '']
      returnLines.push('Book,Member,Membership ID,Borrowed At,Due At,Returned At,Status')
      returnLines.push(...loanData.filter((loan) => loan.returnedAt).map((loan) => [
        safeCsv(loan.book?.title || ''),
        safeCsv(loan.member?.fullName || ''),
        safeCsv(loan.member?.membershipId || ''),
        safeCsv(loan.borrowedAt ? new Date(loan.borrowedAt).toLocaleString() : ''),
        safeCsv(loan.dueAt ? new Date(loan.dueAt).toLocaleString() : ''),
        safeCsv(loan.returnedAt ? new Date(loan.returnedAt).toLocaleString() : ''),
        safeCsv(loan.status || ''),
      ].join(',')))

      const content = [...bookLines, ...memberLines, ...borrowLines, ...returnLines].join('\n')
      downloadFile(`LibroSphere_Report_${formatDateCompact(new Date())}.csv`, content, 'text/csv;charset=utf-8;')
    } catch (err) {
      console.error(err)
      toast.error('Failed to export CSV')
    }
  }

  return (
    <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.3 }} className="space-y-6">
      <div className="rounded-[24px] border border-[var(--color-border)] bg-[var(--color-card)] p-6 shadow-sm sm:p-8">
        <div className="flex items-start justify-between gap-6">
          <div>
            <p className="text-sm uppercase tracking-[0.28em] text-[var(--color-primary)]">Reports</p>
            <h1 className="mt-3 text-2xl font-semibold text-[var(--color-text)] sm:text-3xl">Library activity reports and statistics.</h1>
          </div>
          <div className="flex flex-wrap items-center gap-3">
            <button onClick={generateLibraryPDF} className="inline-flex items-center gap-2 rounded-full bg-[var(--color-primary)] px-4 py-2 text-sm font-medium text-white transition hover:opacity-90">
              📄 Export PDF
            </button>
            <button onClick={exportLibraryCSV} className="inline-flex items-center gap-2 rounded-full border border-[var(--color-border)] bg-[var(--color-background)] px-4 py-2 text-sm font-medium transition hover:bg-[var(--color-border)]">
              📊 Export CSV
            </button>
          </div>
        </div>
      </div>

      <div className="grid gap-4 md:grid-cols-3 xl:grid-cols-6">
        <div className="rounded-[20px] border border-[var(--color-border)] bg-[var(--color-card)] p-5 shadow-sm">
          <p className="text-sm uppercase tracking-[0.24em] text-[var(--color-primary)]">Total Borrows</p>
          <p className="mt-3 text-2xl font-semibold text-[var(--color-text)]">{summary ? summary.totalBorrows : '—'}</p>
        </div>
        <div className="rounded-[20px] border border-[var(--color-border)] bg-[var(--color-card)] p-5 shadow-sm">
          <p className="text-sm uppercase tracking-[0.24em] text-[var(--color-primary)]">Total Returns</p>
          <p className="mt-3 text-2xl font-semibold text-[var(--color-text)]">{summary ? summary.totalReturns : '—'}</p>
        </div>
        <div className="rounded-[20px] border border-[var(--color-border)] bg-[var(--color-card)] p-5 shadow-sm">
          <p className="text-sm uppercase tracking-[0.24em] text-[var(--color-primary)]">Overdue Books</p>
          <p className="mt-3 text-2xl font-semibold text-[var(--color-text)]">{summary ? summary.overdueLoans : '—'}</p>
        </div>
        <div className="rounded-[20px] border border-[var(--color-border)] bg-[var(--color-card)] p-5 shadow-sm">
          <p className="text-sm uppercase tracking-[0.24em] text-[var(--color-primary)]">Total Books</p>
          <p className="mt-3 text-2xl font-semibold text-[var(--color-text)]">{summary ? summary.totalBooks : '—'}</p>
        </div>
        <div className="rounded-[20px] border border-[var(--color-border)] bg-[var(--color-card)] p-5 shadow-sm">
          <p className="text-sm uppercase tracking-[0.24em] text-[var(--color-primary)]">Registered Members</p>
          <p className="mt-3 text-2xl font-semibold text-[var(--color-text)]">{summary ? summary.totalMembers : '—'}</p>
        </div>
        <div className="rounded-[20px] border border-[var(--color-border)] bg-[var(--color-card)] p-5 shadow-sm">
          <p className="text-sm uppercase tracking-[0.24em] text-[var(--color-primary)]">Return Rate</p>
          <p className="mt-3 text-2xl font-semibold text-[var(--color-text)]">{summary ? `${summary.returnRate}%` : '—'}</p>
        </div>
      </div>

      <div className="rounded-[24px] border border-[var(--color-border)] bg-[var(--color-card)] p-5 shadow-sm">
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold text-[var(--color-text)]">Most Borrowed Books</h2>
          <div className="flex items-center gap-3">
            <select className="rounded-[12px] border border-[var(--color-border)] bg-[var(--color-background)] px-3 py-2 text-sm">
              <option>Top 5</option>
            </select>
          </div>
        </div>
        <div className="mt-4 divide-y divide-[var(--color-border)]">
          {popular.length === 0 ? <div className="py-6 text-center text-[var(--color-text-2)]">No data</div> : popular.map((p, i) => (
            <div key={p._id || i} className="flex items-center justify-between py-3">
              <div className="flex items-center gap-3">
                <div className="w-8 text-sm text-[var(--color-text-2)]">#{i + 1}</div>
                <div>
                  <div className="font-semibold">{p.title}</div>
                  <div className="text-sm text-[var(--color-text-2)]">{p.author}</div>
                </div>
              </div>
              <div className="rounded-full bg-[var(--color-background)] px-3 py-1 text-sm">{p.count} Borrows</div>
            </div>
          ))}
        </div>
      </div>

      <div className="grid gap-4">
        <div className="rounded-[24px] border border-[var(--color-border)] bg-[var(--color-card)] p-5 shadow-sm">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-semibold text-[var(--color-text)]">Member Activity Report</h2>
            <div className="flex items-center gap-2">
              <select className="rounded-[12px] border border-[var(--color-border)] bg-[var(--color-background)] px-3 py-2 text-sm">
                <option>All members</option>
              </select>
            </div>
          </div>
          <div className="mt-4 overflow-x-auto">
            <table className="w-full table-auto">
              <thead>
                <tr className="text-left text-sm text-[var(--color-text-2)]">
                  <th className="py-2">Member</th>
                  <th>Membership ID</th>
                  <th>Books Borrowed</th>
                  <th>Books Returned</th>
                  <th>Currently Borrowed</th>
                  <th>Overdue</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {members.length === 0 ? (
                  <tr><td colSpan={7} className="py-6 text-center text-[var(--color-text-2)]">No members</td></tr>
                ) : members.map((m) => (
                  <tr key={m._id} className="border-t border-[var(--color-border)]">
                    <td className="py-3 align-top">
                      <div className="font-semibold text-[var(--color-text)]">{m.fullName}</div>
                    </td>
                    <td className="align-top">{m.membershipId}</td>
                    <td className="align-top">{m.totalBorrowedCount ?? 0}</td>
                    <td className="align-top">{m.totalBorrowedCount && m.currentBorrowedCount != null ? (m.totalBorrowedCount - m.currentBorrowedCount) : 0}</td>
                    <td className="align-top">{m.currentBorrowedCount ?? 0}</td>
                    <td className="align-top">{m.overdueCount ?? 0}</td>
                    <td className="align-top flex gap-2">
                      <button onClick={() => setViewMember(m)} className="rounded-full bg-[var(--color-background)] px-3 py-2 text-sm">👁 View</button>
                      <button onClick={() => generateMemberPDF(m)} className="rounded-full bg-[var(--color-background)] px-3 py-2 text-sm">📄 PDF</button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <Modal open={Boolean(viewMember)} onClose={() => setViewMember(null)} title="Member Report">
        {viewMember && (
          <MemberReportModal member={viewMember} onClose={() => setViewMember(null)} />
        )}
      </Modal>
    </motion.div>
  )
}

function MemberReportModal({ member }) {
  const [history, setHistory] = useState([])
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    const load = async () => {
      setLoading(true)
      try {
        const res = await fetchLoans({ member: member._id, page: 1, limit: 1000 })
        setHistory(res?.data || [])
      } catch (err) {
        console.error(err)
      } finally {
        setLoading(false)
      }
    }
    load()
  }, [member._id])

  return (
    <div className="space-y-4 max-h-[70vh] overflow-y-auto">
      <div>
        <p className="text-sm text-[var(--color-text-2)]">Member Name</p>
        <p className="mt-1 font-semibold text-[var(--color-text)]">{member.fullName}</p>
      </div>
      <div className="grid grid-cols-2 gap-3">
        <div>
          <p className="text-sm text-[var(--color-text-2)]">Membership ID</p>
          <p className="mt-1 font-semibold text-[var(--color-text)]">{member.membershipId}</p>
        </div>
        <div>
          <p className="text-sm text-[var(--color-text-2)]">Email</p>
          <p className="mt-1 font-semibold text-[var(--color-text)]">{member.email}</p>
        </div>
      </div>
      <div className="grid grid-cols-2 gap-3">
        <div>
          <p className="text-sm text-[var(--color-text-2)]">Phone</p>
          <p className="mt-1 font-semibold text-[var(--color-text)]">{member.phone || '—'}</p>
        </div>
        <div>
          <p className="text-sm text-[var(--color-text-2)]">Address</p>
          <p className="mt-1 font-semibold text-[var(--color-text)]">{member.address || '—'}</p>
        </div>
      </div>

      <div className="grid grid-cols-4 gap-3">
        <div className="rounded-lg bg-[var(--color-background)] p-3 text-center">
          <div className="text-sm text-[var(--color-text-2)]">Books Borrowed</div>
          <div className="mt-1 font-semibold">{member.totalBorrowedCount ?? 0}</div>
        </div>
        <div className="rounded-lg bg-[var(--color-background)] p-3 text-center">
          <div className="text-sm text-[var(--color-text-2)]">Books Returned</div>
          <div className="mt-1 font-semibold">{(member.totalBorrowedCount ?? 0) - (member.currentBorrowedCount ?? 0)}</div>
        </div>
        <div className="rounded-lg bg-[var(--color-background)] p-3 text-center">
          <div className="text-sm text-[var(--color-text-2)]">Currently Borrowed</div>
          <div className="mt-1 font-semibold">{member.currentBorrowedCount ?? 0}</div>
        </div>
        <div className="rounded-lg bg-[var(--color-background)] p-3 text-center">
          <div className="text-sm text-[var(--color-text-2)]">Overdue Books</div>
          <div className="mt-1 font-semibold">{member.overdueCount ?? 0}</div>
        </div>
      </div>

      <div>
        <h3 className="text-lg font-semibold">Borrowing History</h3>
        {loading ? <div className="mt-4 text-[var(--color-text-2)]">Loading...</div> : history.length === 0 ? (
          <div className="mt-4 text-[var(--color-text-2)]">No history</div>
        ) : (
          <div className="mt-4 space-y-3">
            {history.sort((a,b)=>new Date(b.borrowedAt)-new Date(a.borrowedAt)).map((h) => (
              <div key={h._id} className="rounded-lg border border-[var(--color-border)] p-3">
                <div className="font-semibold">{h.book?.title}</div>
                <div className="text-sm text-[var(--color-text-2)]">Borrowed: {formatDateShort(h.borrowedAt)} · Due: {formatDateShort(h.dueAt)} · Returned: {h.returnedAt ? formatDateShort(h.returnedAt) : '—'}</div>
                <div className="mt-2"><span className={`rounded-full px-2 py-1 text-sm ${h.status === 'returned' ? 'bg-emerald-100 text-emerald-700' : (!h.returnedAt && new Date(h.dueAt) < new Date() ? 'bg-red-100 text-red-600' : 'bg-yellow-100')}`}>{h.status === 'returned' ? 'Returned' : (!h.returnedAt && new Date(h.dueAt) < new Date() ? 'Overdue' : 'Borrowed')}</span></div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}
